package de.mineking.manager.api.error

import io.javalin.http.HttpStatus

enum class ErrorResponseType(val status: HttpStatus) {
	UNKNOWN(HttpStatus.INTERNAL_SERVER_ERROR),

	INVALID_REQUEST(HttpStatus.BAD_REQUEST),

	MISSING_TOKEN(HttpStatus.UNAUTHORIZED),
	INVALID_TOKEN(HttpStatus.UNAUTHORIZED),
	TOKEN_EXPIRED(HttpStatus.UNAUTHORIZED),
	MISSING_ACCESS(HttpStatus.FORBIDDEN),

	WRONG_PASSWORD(HttpStatus.BAD_REQUEST),

	SKILL_NOT_FOUND(HttpStatus.NOT_FOUND),
	SKILL_ALREADY_EXISTS(HttpStatus.CONFLICT),
	USER_NOT_FOUND(HttpStatus.NOT_FOUND),
	USER_ALREADY_EXISTS(HttpStatus.CONFLICT),
	TEAM_NOT_FOUND(HttpStatus.NOT_FOUND),
	TEAM_ALREADY_EXISTS(HttpStatus.CONFLICT),
	MEETING_NOT_FOUND(HttpStatus.NOT_FOUND),
	MEETING_ALREADY_EXISTS(HttpStatus.CONFLICT),

	ALREADY_PARTICIPATING(HttpStatus.CONFLICT),
	PARTICIPANT_NOT_FOUND(HttpStatus.CONFLICT)
}